# run some tests here


FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
LABEL user=saravanan role=tester
WORKDIR /sourcetotest
COPY . .
RUN dotnet test -l "trx;LogFileName=TestResults.xml"
CMD  cp -a /sourcetotest/. /var/jenkins_home/workspace/dockerbuildpipeline/jenkinsOut/sourcetotest