# run some tests here


FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
LABEL user=saravanan role=tester
WORKDIR /sourcetotest
COPY . .
RUN dotnet test --no-build -l "trx;LogFileName=TestResults.xml"
cmd ["/bin/bash"]