# run build the code here


FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
LABEL user=saravanan role=builder
WORKDIR /sourcetobuild
COPY . .
RUN dotnet build -c Release
CMD  cp -R /sourcetobuild /var/jenkins_home/workspace/dockerbuildpipeline/jenkinsOut/sourcetobuild