# run some tests here


FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
LABEL user=saravanan role=publish
WORKDIR /sourcetopublish
COPY . .
RUN dotnet publish  -o /app
CMD  cp -a /sourcetopublish/. /var/jenkins_home/workspace/dockerbuildpipeline/jenkinsOut/sourcetopublish